# Generated by Django 4.1.13 on 2024-03-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('SUBSCRIBER', 'SUBSCRIBER')], default='SUBSCRIBER', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('photo_url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_id', models.CharField(max_length=100)),
                ('Plan_Title', models.CharField(max_length=100)),
                ('Plan_subHeader', models.CharField(max_length=100)),
                ('Plan_Price', models.CharField(max_length=100)),
                ('AccountType', models.CharField(max_length=100)),
                ('Plan_Feature', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexminer.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscriber_id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='paid', max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forexminer.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forexminer.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('feedback_type', models.CharField(default='feedback', max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('status', models.CharField(default='not responded', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reciever_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexminer.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='FaQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaQ_id', models.CharField(max_length=100)),
                ('Questions', models.CharField(max_length=100)),
                ('Answers', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexminer.customuser')),
            ],
        ),
    ]
