# Generated by Django 4.1.13 on 2024-03-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forexminer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexminer.customuser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reciever_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexminer.customuser'),
        ),
        migrations.AddField(
            model_name='plans',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexminer.customuser'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forexminer.plans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forexminer.customuser'),
            preserve_default=False,
        ),
    ]
