# Generated by Django 4.1.13 on 2024-06-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexminer', '0002_faqs_created_by_feedback_reciever_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('subscriber', 'subscriber')], default='subscriber', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
